### ISSUE TITLE
error description coming from GIT

### ISSUE THREAD

**Issue by jotka** [Nykredit/gulp-release#13]
Hi Thor;
It would be nice if the git command fails, let it be `pull` or `push` to have the command output in the log file, instead of just `git push exited with code 1`. We had some support tickets related to failing git command and having the above would speed things up. 

Maybe I will just create a PR for that :)

**Comment by clausfod** [comment]
It is supported - set the debug property to true. See readme file :-)

**Comment by jotka** [comment]
Ah, ok :)
