### ISSUE TITLE
Add output stdout and stderr from git exec commands to gulp console output

### ISSUE THREAD

**Issue by Mortenagoda** [Nykredit/gulp-release#8]
Currently, when git commands fails (returncode <> 0) output only states the return code. The return code is always the same when a git command fails.

Example error situations that is not revealed by the output:
git tag -- tag already exists
git commit -- nothing changed

Output from the release feature should also contain the output printed to stdout and stderr from external executions, e.g., the git commands executed.

**Comment by langecode** [comment]
Pul request #7 actually should solve this one.
